--  数据同步前置条件

ALTER TABLE APP ADD CREATE_TIME TIMESTAMP(6);
COMMENT ON COLUMN APP.CREATE_TIME IS '创建时间';
ALTER TABLE APP ADD UPDATE_TIME TIMESTAMP(6);
COMMENT ON COLUMN APP.UPDATE_TIME IS '修改时间';

ALTER TABLE REG_USER ADD CREATE_TIME TIMESTAMP(6);
COMMENT ON COLUMN REG_USER.CREATE_TIME IS '创建时间';
ALTER TABLE REG_USER ADD UPDATE_TIME TIMESTAMP(6);
COMMENT ON COLUMN REG_USER.UPDATE_TIME IS '修改时间';

ALTER TABLE TRAID_PERSON ADD CREATE_TIME TIMESTAMP(6);
COMMENT ON COLUMN TRAID_PERSON.CREATE_TIME IS '创建时间';
ALTER TABLE TRAID_PERSON ADD UPDATE_TIME TIMESTAMP(6);
COMMENT ON COLUMN TRAID_PERSON.UPDATE_TIME IS '修改时间';

ALTER TABLE TRIAD_DEPT ADD CREATE_TIME TIMESTAMP(6);
COMMENT ON COLUMN TRIAD_DEPT.CREATE_TIME IS '创建时间';
ALTER TABLE TRIAD_DEPT ADD UPDATE_TIME TIMESTAMP(6);
COMMENT ON COLUMN TRIAD_DEPT.UPDATE_TIME IS '修改时间';

ALTER TABLE TRIAD_ENTERPRISE_INFO ADD CREATE_TIME TIMESTAMP(6);
COMMENT ON COLUMN TRIAD_ENTERPRISE_INFO.CREATE_TIME IS '创建时间';
ALTER TABLE TRIAD_ENTERPRISE_INFO ADD UPDATE_TIME TIMESTAMP(6);
COMMENT ON COLUMN TRIAD_ENTERPRISE_INFO.UPDATE_TIME IS '修改时间';

ALTER TABLE TRIAD_MYSELF_INFO ADD CREATE_TIME TIMESTAMP(6);
COMMENT ON COLUMN TRIAD_MYSELF_INFO.CREATE_TIME IS '创建时间';
ALTER TABLE TRIAD_MYSELF_INFO ADD UPDATE_TIME TIMESTAMP(6);
COMMENT ON COLUMN TRIAD_MYSELF_INFO.UPDATE_TIME IS '修改时间';

ALTER TABLE WEBSITE ADD CREATE_TIME TIMESTAMP(6);
COMMENT ON COLUMN WEBSITE.CREATE_TIME IS '创建时间';
ALTER TABLE WEBSITE ADD UPDATE_TIME TIMESTAMP(6);
COMMENT ON COLUMN WEBSITE.UPDATE_TIME IS '修改时间';







CREATE OR REPLACE TRIGGER APP_TRIGGER  
BEFORE INSERT OR UPDATE ON APP FOR EACH ROW
BEGIN
  IF UPDATING  THEN
      SELECT SYSDATE INTO :NEW.UPDATE_TIME FROM DUAL;
    ELSE
      SELECT SYSDATE INTO :NEW.CREATE_TIME FROM DUAL;
  END IF;
END;

CREATE OR REPLACE TRIGGER REG_USER_TRIGGER  
BEFORE INSERT OR UPDATE ON REG_USER FOR EACH ROW
BEGIN
  IF UPDATING  THEN
      SELECT SYSDATE INTO :NEW.UPDATE_TIME FROM DUAL;
    ELSE
      SELECT SYSDATE INTO :NEW.CREATE_TIME FROM DUAL;
  END IF;
END;

CREATE OR REPLACE TRIGGER TRAID_PERSON_TRIGGER  
BEFORE INSERT OR UPDATE ON TRAID_PERSON FOR EACH ROW
BEGIN
  IF UPDATING  THEN
      SELECT SYSDATE INTO :NEW.UPDATE_TIME FROM DUAL;
    ELSE
      SELECT SYSDATE INTO :NEW.CREATE_TIME FROM DUAL;
  END IF;
END;

CREATE OR REPLACE TRIGGER TRIAD_DEPT_TRIGGER  
BEFORE INSERT OR UPDATE ON TRIAD_DEPT FOR EACH ROW
BEGIN
  IF UPDATING  THEN
      SELECT SYSDATE INTO :NEW.UPDATE_TIME FROM DUAL;
    ELSE
      SELECT SYSDATE INTO :NEW.CREATE_TIME FROM DUAL;
  END IF;
END;

CREATE OR REPLACE TRIGGER TRIAD_ENTERPRISE_INFO_TRIGGER  
BEFORE INSERT OR UPDATE ON TRIAD_ENTERPRISE_INFO FOR EACH ROW
BEGIN
  IF UPDATING  THEN
      SELECT SYSDATE INTO :NEW.UPDATE_TIME FROM DUAL;
    ELSE
      SELECT SYSDATE INTO :NEW.CREATE_TIME FROM DUAL;
  END IF;
END;

CREATE OR REPLACE TRIGGER TRIAD_MYSELF_INFO_TRIGGER  
BEFORE INSERT OR UPDATE ON TRIAD_MYSELF_INFO FOR EACH ROW
BEGIN
  IF UPDATING  THEN
      SELECT SYSDATE INTO :NEW.UPDATE_TIME FROM DUAL;
    ELSE
      SELECT SYSDATE INTO :NEW.CREATE_TIME FROM DUAL;
  END IF;
END;

CREATE OR REPLACE TRIGGER WEBSITE_TRIGGER  
BEFORE INSERT OR UPDATE ON WEBSITE FOR EACH ROW
BEGIN
  IF UPDATING  THEN
      SELECT SYSDATE INTO :NEW.UPDATE_TIME FROM DUAL;
    ELSE
      SELECT SYSDATE INTO :NEW.CREATE_TIME FROM DUAL;
  END IF;
END;

CREATE TABLE APP_UP AS SELECT * FROM APP WHERE 1=2;
CREATE TABLE REG_USER_UP AS SELECT * FROM REG_USER WHERE 1=2;
CREATE TABLE TRAID_PERSON_UP AS SELECT * FROM TRAID_PERSON WHERE 1=2;
CREATE TABLE TRIAD_DEPT_UP AS SELECT * FROM TRIAD_DEPT WHERE 1=2;
CREATE TABLE TRIAD_ENTERPRISE_INFO_UP AS SELECT * FROM TRIAD_ENTERPRISE_INFO WHERE 1=2;
CREATE TABLE TRIAD_MYSELF_INFO_UP AS SELECT * FROM TRIAD_MYSELF_INFO WHERE 1=2;
CREATE TABLE WEBSITE_UP AS SELECT * FROM WEBSITE WHERE 1=2;








-- 最后执行 更新数据合并
MERGE INTO APP A USING APP_UP B ON (A.ID = B.ID) WHEN MATCHED THEN UPDATE SET A.NAME= B.NAME,A.ICP_RECORD_CODE= B.ICP_RECORD_CODE,A.DEVELOPER_NAME= B.DEVELOPER_NAME,A.APP_VERSION= B.APP_VERSION,A.OPEN_DATE= B.OPEN_DATE,A.ADD_TIME= B.ADD_TIME,A.JOIN_AREA_RULE= B.JOIN_AREA_RULE,A.PROVINCE_CODE= B.PROVINCE_CODE,A.CITY_CODE= B.CITY_CODE,A.AREA_CODE= B.AREA_CODE,A.JOIN_NAME= B.JOIN_NAME,A.JOIN_TYPE= B.JOIN_TYPE,A.IF_SERVICE_INTERACTIVE= B.IF_SERVICE_INTERACTIVE,A.IF_SERVICE_FORUM= B.IF_SERVICE_FORUM,A.SERVICE_CONTENT= B.SERVICE_CONTENT,A.IF_INFORMATION_SERVICE= B.IF_INFORMATION_SERVICE,A.INFORMATION_CONTENT= B.INFORMATION_CONTENT,A.IF_FRONT_ACCESS= B.IF_FRONT_ACCESS,A.ACCESS_CONTENT= B.ACCESS_CONTENT,A.LANGUAGE= B.LANGUAGE,A.NEWS= B.NEWS,A.PUBLISH= B.PUBLISH,A.EDUCATION= B.EDUCATION,A.SPORTS= B.SPORTS,A.MEDICAL= B.MEDICAL,A.OTHER= B.OTHER,A.BUSINESS_TYPE= B.BUSINESS_TYPE,A.WEBSITE_TYPE= B.WEBSITE_TYPE,A.REG_USER_ID= B.REG_USER_ID,A.URGENT_CONTACTS_NAME1= B.URGENT_CONTACTS_NAME1,A.URGENT_CONTACTS_IDTYPE1= B.URGENT_CONTACTS_IDTYPE1,A.URGENT_CONTACTS_IDCODE1= B.URGENT_CONTACTS_IDCODE1,A.URGENT_CONTACTS_PHONE1= B.URGENT_CONTACTS_PHONE1,A.URGENT_CONTACTS_NAME2= B.URGENT_CONTACTS_NAME2,A.URGENT_CONTACTS_IDTYPE2= B.URGENT_CONTACTS_IDTYPE2,A.URGENT_CONTACTS_IDCODE2= B.URGENT_CONTACTS_IDCODE2,A.URGENT_CONTACTS_PHONE2= B.URGENT_CONTACTS_PHONE2,A.IF_MULTI_MEDIA= B.IF_MULTI_MEDIA,A.APP_AREA_CODE= B.APP_AREA_CODE,A.POLICE_RECORD_CODE= B.POLICE_RECORD_CODE,A.IF_NEWSMEDIA= B.IF_NEWSMEDIA,A.NEWMEDIA_CODE= B.NEWMEDIA_CODE,A.NEWMEDIA_TYPE= B.NEWMEDIA_TYPE,A.NEWMEDIA_FILEPATH= B.NEWMEDIA_FILEPATH,A.IF_DANGEROUS_EXPLOSION= B.IF_DANGEROUS_EXPLOSION,A.MAIN_DOMAIN= B.MAIN_DOMAIN,A.IPS= B.IPS,A.TYPE_CONTENT= B.TYPE_CONTENT,A.WEBSITE_COUNTRY= B.WEBSITE_COUNTRY,A.WEBSITE_ADDRESS= B.WEBSITE_ADDRESS,A.ISCDN= B.ISCDN,A.SERVICE_NAME= B.SERVICE_NAME,A.DOMAIN_COUNTRY= B.DOMAIN_COUNTRY,A.DOMAIN_ADDRESS= B.DOMAIN_ADDRESS,A.POLICE_CODE= B.POLICE_CODE,A.POLICE_NAME= B.POLICE_NAME,A.STATE= B.STATE,A.CHECK_DATE= B.CHECK_DATE,A.CHECK_PERSON= B.CHECK_PERSON,A.CHECK_PASS= B.CHECK_PASS,A.NO_PASS_REASON= B.NO_PASS_REASON,A.PASSWORD= B.PASSWORD,A.IF_REGISTER_FUN= B.IF_REGISTER_FUN,A.USERNAME= B.USERNAME,A.ICON= B.ICON,A.DANGEROUS_TYPE= B.DANGEROUS_TYPE,A.INFOPROCESS_PATH= B.INFOPROCESS_PATH,A.IP_STATE= B.IP_STATE,A.IP_ADDRESS= B.IP_ADDRESS,A.IPV6= B.IPV6,A.UPDATE_TIME= B.UPDATE_TIME,A.ICP_RECORD_CODE_NUMA= B.ICP_RECORD_CODE_NUMA,A.ICP_RECORD_CODE_NUMB= B.ICP_RECORD_CODE_NUMB,A.ICP_RECORD_CODE_NUMAB= B.ICP_RECORD_CODE_NUMAB,A.DATA_SOURCE= B.DATA_SOURCE,A.NO_NEWMEDIA_FILEPATH= B.NO_NEWMEDIA_FILEPATH,A.CREATE_TIME= B.CREATE_TIME;
MERGE INTO REG_USER A USING REG_USER_UP B ON (A.ID = B.ID) WHEN MATCHED THEN UPDATE SET A.NAME= B.NAME,A.PASSWORD= B.PASSWORD,A.REALNAME= B.REALNAME,A.AREA_CODE= B.AREA_CODE,A.RECORD_TYPE= B.RECORD_TYPE,A.ID_CARD= B.ID_CARD,A.CELL_NUMBER= B.CELL_NUMBER,A.MAIL= B.MAIL,A.ADDRESS= B.ADDRESS,A.REG_TIME= B.REG_TIME,A.STATUS= B.STATUS,A.LAST_LOG_TIME= B.LAST_LOG_TIME,A.FIRST_PSWD= B.FIRST_PSWD,A.RECORD_WAY= B.RECORD_WAY,A.IS_SAFE_CHECK= B.IS_SAFE_CHECK,A.VERIFY= B.VERIFY,A.VERIFY_TIME= B.VERIFY_TIME,A.SEND_NUMBER= B.SEND_NUMBER,A.IMPORT_TYPE= B.IMPORT_TYPE,A.REG_IP= B.REG_IP,A.SESSION_ID= B.SESSION_ID,A.ON_LINE= B.ON_LINE,A.ID_TYPE= B.ID_TYPE,A.WEB_NAME= B.WEB_NAME,A.WEB_ADDR= B.WEB_ADDR,A.FIRST_LAND_TIME= B.FIRST_LAND_TIME,A.ISP_CODE= B.ISP_CODE,A.IS_ABLE= B.IS_ABLE,A.LINK_STATE= B.LINK_STATE,A.PASSWD= B.PASSWD,A.OPEN_ID= B.OPEN_ID,A.OPEN_IDS= B.OPEN_IDS,A.CREAT_TIME= B.CREAT_TIME,A.UPDATE_TIME= B.UPDATE_TIME,A.UNIQUE_KEY= B.UNIQUE_KEY,A.TYPE= B.TYPE,A.TYPE_BASE= B.TYPE_BASE,A.WIRELESSNET_STATE= B.WIRELESSNET_STATE,A.CHANNEL_ID= B.CHANNEL_ID,A.CREATE_TIME= B.CREATE_TIME;
MERGE INTO TRAID_PERSON A USING TRAID_PERSON_UP B ON (A.ID = B.ID) WHEN MATCHED THEN UPDATE SET A.DEPT_NAME= B.DEPT_NAME,A.NAME= B.NAME,A.DUTY= B.DUTY,A.PHONE= B.PHONE,A.USERID= B.USERID,A.TYPE_BASE= B.TYPE_BASE,A.DEPTID= B.DEPTID,A.SON_USER_ID= B.SON_USER_ID,A.CREATE_TIME= B.CREATE_TIME,A.UPDATE_TIME= B.UPDATE_TIME;
MERGE INTO TRIAD_DEPT A USING TRIAD_DEPT_UP B ON (A.ID = B.ID) WHEN MATCHED THEN UPDATE SET A.DEPT_NAME= B.DEPT_NAME,A.DEPT_LEGAL_NAME= B.DEPT_LEGAL_NAME,A.DEPT_LEGAL_GRADE= B.DEPT_LEGAL_GRADE,A.DEPT_LEGAL_PHONE= B.DEPT_LEGAL_PHONE,A.TRIADENID= B.TRIADENID,A.TYPEBASE= B.TYPEBASE,A.SON_USER_ID= B.SON_USER_ID,A.CREATE_TIME= B.CREATE_TIME,A.UPDATE_TIME= B.UPDATE_TIME;
MERGE INTO TRIAD_ENTERPRISE_INFO A USING TRIAD_ENTERPRISE_INFO_UP B ON (A.ID = B.ID) WHEN MATCHED THEN UPDATE SET A.UNIT_NAME= B.UNIT_NAME,A.UNIT_TYPE= B.UNIT_TYPE,A.UNIT_CODE= B.UNIT_CODE,A.UNIT_DOCUMENTS= B.UNIT_DOCUMENTS,A.LEGAL_DAIBIAO_NAME= B.LEGAL_DAIBIAO_NAME,A.UNIT_ADDRESS= B.UNIT_ADDRESS,A.LEGAL_NAME= B.LEGAL_NAME,A.LEGAL_ID_TYPE= B.LEGAL_ID_TYPE,A.LEGAL_ID_CODE= B.LEGAL_ID_CODE,A.LEGAL_ID_TIME= B.LEGAL_ID_TIME,A.LEGAL_ID_PHOTO_ZHENG= B.LEGAL_ID_PHOTO_ZHENG,A.LEGAL_ID_PHOTO_FAN= B.LEGAL_ID_PHOTO_FAN,A.LEGAL_ID_PHOTO_SHOU= B.LEGAL_ID_PHOTO_SHOU,A.LEGAL_PROVINCE= B.LEGAL_PROVINCE,A.LEGAL_CITY= B.LEGAL_CITY,A.LEGAL_COUNTY= B.LEGAL_COUNTY,A.LEGAL_ADDRESS= B.LEGAL_ADDRESS,A.LEGAL_OFFICE_PHONE= B.LEGAL_OFFICE_PHONE,A.LEGAL_PHONE= B.LEGAL_PHONE,A.LEGAL_EMAIL= B.LEGAL_EMAIL,A.USERNAME= B.USERNAME,A.UNIT_PROVINCE= B.UNIT_PROVINCE,A.UNIT_CITY= B.UNIT_CITY,A.UNIT_COUNTY= B.UNIT_COUNTY,A.USERID= B.USERID,A.TYPE_UNIT= B.TYPE_UNIT,A.POLICE_CODE= B.POLICE_CODE,A.ACCREDIT_STATUS= B.ACCREDIT_STATUS,A.ACCREDIT_NAME= B.ACCREDIT_NAME,A.UPATE_DATE= B.UPATE_DATE,A.IS_CHECK= B.IS_CHECK,A.SERVICE_CODE= B.SERVICE_CODE,A.WHITE_LIST= B.WHITE_LIST,A.POINT_X= B.POINT_X,A.POINT_Y= B.POINT_Y,A.REPORTED_STATE= B.REPORTED_STATE,A.REPORTED_MSG= B.REPORTED_MSG,A.POINT_X_GD= B.POINT_X_GD,A.POINT_Y_GD= B.POINT_Y_GD,A.UNIT_REGISTER_PROVINCE= B.UNIT_REGISTER_PROVINCE,A.UNIT_REGISTER_CITY= B.UNIT_REGISTER_CITY,A.UNIT_REGISTER_COUNTY= B.UNIT_REGISTER_COUNTY,A.UNIT_REGISTER_ADDRESS= B.UNIT_REGISTER_ADDRESS,A.WEBAPP_STATE= B.WEBAPP_STATE,A.WEBAPP_REPORTED_STATE= B.WEBAPP_REPORTED_STATE,A.ATTACH_TYPE= B.ATTACH_TYPE,A.UPDATE_CONTENT= B.UPDATE_CONTENT,A.WEB_NAME= B.WEB_NAME,A.APP_NAME= B.APP_NAME,A.REPORTED_TIME= B.REPORTED_TIME,A.ACCREDIT_LEVEL= B.ACCREDIT_LEVEL,A.DATA_SOURCE= B.DATA_SOURCE,A.BUDUNITID= B.BUDUNITID,A.IS_SPECIAL= B.IS_SPECIAL,A.IS_DSF= B.IS_DSF,A.CREATE_TIME= B.CREATE_TIME,A.UPDATE_TIME= B.UPDATE_TIME;
MERGE INTO TRIAD_MYSELF_INFO A USING TRIAD_MYSELF_INFO_UP B ON (A.ID = B.ID) WHEN MATCHED THEN UPDATE SET A.NAME= B.NAME,A.ID_TYPE= B.ID_TYPE,A.ID_CODE= B.ID_CODE,A.ID_CARD_ZHENG= B.ID_CARD_ZHENG,A.ID_CARD_FAN= B.ID_CARD_FAN,A.ID_CARD_SHOU= B.ID_CARD_SHOU,A.PROVINCE= B.PROVINCE,A.CITY= B.CITY,A.COUNTY= B.COUNTY,A.ADDRESS= B.ADDRESS,A.OFFIC_PHONE= B.OFFIC_PHONE,A.PHONE= B.PHONE,A.EMAIL= B.EMAIL,A.REGUSERNAME= B.REGUSERNAME,A.ID_TIME= B.ID_TIME,A.USERID= B.USERID,A.POLICE_CODE= B.POLICE_CODE,A.IS_CHECK= B.IS_CHECK,A.SERVICE_CODE= B.SERVICE_CODE,A.WHITE_LIST= B.WHITE_LIST,A.POINT_X= B.POINT_X,A.POINT_Y= B.POINT_Y,A.POINT_X_GD= B.POINT_X_GD,A.POINT_Y_GD= B.POINT_Y_GD,A.WEBAPP_STATE= B.WEBAPP_STATE,A.WEBAPP_REPORTED_STATE= B.WEBAPP_REPORTED_STATE,A.UPDATE_CONTENT= B.UPDATE_CONTENT,A.DATA_SOURCE= B.DATA_SOURCE,A.BUDUNITID= B.BUDUNITID,A.IS_DSF= B.IS_DSF,A.CREATE_TIME= B.CREATE_TIME,A.UPDATE_TIME= B.UPDATE_TIME;
MERGE INTO WEBSITE A USING WEBSITE_UP B ON (A.ID = B.ID) WHEN MATCHED THEN UPDATE SET A.UNIT= B.UNIT,A.NAME= B.NAME,A.IF_ICP_RECORD= B.IF_ICP_RECORD,A.ICP_RECORD_CODE= B.ICP_RECORD_CODE,A.MAIN_DOMAIN= B.MAIN_DOMAIN,A.VICE_DOMAIN= B.VICE_DOMAIN,A.DOMAIN_CERTIFICATE= B.DOMAIN_CERTIFICATE,A.IPS= B.IPS,A.JOIN_AREA_RULE= B.JOIN_AREA_RULE,A.PROVINCE_CODE= B.PROVINCE_CODE,A.CITY_CODE= B.CITY_CODE,A.AREA_CODE= B.AREA_CODE,A.JOIN_NAME= B.JOIN_NAME,A.JOIN_TYPE= B.JOIN_TYPE,A.APP_ID= B.APP_ID,A.IF_SERVICE_INTERACTIVE= B.IF_SERVICE_INTERACTIVE,A.IF_SERVICE_FORUM= B.IF_SERVICE_FORUM,A.SERVICE_CONTENT= B.SERVICE_CONTENT,A.IFINFORMATION_SERVICE= B.IFINFORMATION_SERVICE,A.INFORMATION_CONTENT= B.INFORMATION_CONTENT,A.IFFRONTACCESS= B.IFFRONTACCESS,A.ACCESSCONTENT= B.ACCESSCONTENT,A.LANGUAGES= B.LANGUAGES,A.REG_USER_ID= B.REG_USER_ID,A.SERVICE_CODE= B.SERVICE_CODE,A.OPEN_DATE= B.OPEN_DATE,A.UPDATE_TIME= B.UPDATE_TIME,A.URGENT_CONTACTS_NAME1= B.URGENT_CONTACTS_NAME1,A.URGENT_CONTACTS_IDTYPE1= B.URGENT_CONTACTS_IDTYPE1,A.URGENT_CONTACTS_IDCODE1= B.URGENT_CONTACTS_IDCODE1,A.URGENT_CONTACTS_PHONE1= B.URGENT_CONTACTS_PHONE1,A.URGENT_CONTACTS_NAME2= B.URGENT_CONTACTS_NAME2,A.URGENT_CONTACTS_IDTYPE2= B.URGENT_CONTACTS_IDTYPE2,A.URGENT_CONTACTS_IDCODE2= B.URGENT_CONTACTS_IDCODE2,A.URGENT_CONTACTS_PHONE2= B.URGENT_CONTACTS_PHONE2,A.NEWS= B.NEWS,A.PUBLISH= B.PUBLISH,A.EDUCATION= B.EDUCATION,A.SPORTS= B.SPORTS,A.MEDICAL= B.MEDICAL,A.OTHER= B.OTHER,A.DOMAIN_REG_RULE= B.DOMAIN_REG_RULE,A.DR_PROVINCE_CODE= B.DR_PROVINCE_CODE,A.DR_CITY_CODE= B.DR_CITY_CODE,A.DR_AREA_CODE= B.DR_AREA_CODE,A.DOMAIN_REG_NAME= B.DOMAIN_REG_NAME,A.BUSINESS_TYPE= B.BUSINESS_TYPE,A.WEBSITE_TYPE= B.WEBSITE_TYPE,A.IF_MULTI_MEDIA= B.IF_MULTI_MEDIA,A.WEB_AREA_CODE= B.WEB_AREA_CODE,A.IF_DANGEROUS_EXPLOSION= B.IF_DANGEROUS_EXPLOSION,A.IF_NEWSMEDIA= B.IF_NEWSMEDIA,A.NEWMEDIA_CODE= B.NEWMEDIA_CODE,A.NEWMEDIA_TYPE= B.NEWMEDIA_TYPE,A.NEWMEDIA_FILEPATH= B.NEWMEDIA_FILEPATH,A.POLICE_RECORD_CODE= B.POLICE_RECORD_CODE,A.TYPE_CONTENT= B.TYPE_CONTENT,A.WEBSITE_COUNTRY= B.WEBSITE_COUNTRY,A.WEBSITE_ADDRESS= B.WEBSITE_ADDRESS,A.ISCDN= B.ISCDN,A.SERVICE_NAME= B.SERVICE_NAME,A.DOMAIN_COUNTRY= B.DOMAIN_COUNTRY,A.DOMAIN_ADDRESS= B.DOMAIN_ADDRESS,A.POLICE_NAME= B.POLICE_NAME,A.POLICE_CODE= B.POLICE_CODE,A.SIGN= B.SIGN,A.REPORTED_STATE= B.REPORTED_STATE,A.REPORTED_MSG= B.REPORTED_MSG,A.ADD_TIME= B.ADD_TIME,A.DELETE_REQUEST_USER= B.DELETE_REQUEST_USER,A.DELETE_REQUEST_TIME= B.DELETE_REQUEST_TIME,A.STATE= B.STATE,A.CHECK_DATE= B.CHECK_DATE,A.CHECK_PERSON= B.CHECK_PERSON,A.CHECK_PASS= B.CHECK_PASS,A.NO_PASS_REASON= B.NO_PASS_REASON,A.IF_REGISTER_FUN= B.IF_REGISTER_FUN,A.USERNAME= B.USERNAME,A.PASSWORD= B.PASSWORD,A.IP_STATE= B.IP_STATE,A.IP_ADDRESS= B.IP_ADDRESS,A.REPORTED_TIME= B.REPORTED_TIME,A.DANGEROUS_TYPE= B.DANGEROUS_TYPE,A.INFOPROCESS_PATH= B.INFOPROCESS_PATH,A.IPV6= B.IPV6,A.ICP_RECORD_CODE_NUMA= B.ICP_RECORD_CODE_NUMA,A.ICP_RECORD_CODE_NUMB= B.ICP_RECORD_CODE_NUMB,A.ICP_RECORD_CODE_NUMAB= B.ICP_RECORD_CODE_NUMAB,A.DATA_SOURCE= B.DATA_SOURCE,A.BUDUNITID= B.BUDUNITID,A.NO_NEWMEDIA_FILEPATH= B.NO_NEWMEDIA_FILEPATH,A.CREATE_TIME= B.CREATE_TIME;












